image_width: 1280
image_height: 720
camera_name: global_cam
camera_matrix:
  rows: 3
  cols: 3
  data: [974.7798 ,   0.     , 625.94772,
           0.     , 979.87752, 342.09218,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.042615, -0.104423, -0.003163, -0.006316, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [972.07593,   0.     , 616.47216,   0.     ,
           0.     , 986.72479, 339.84042,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
